# Generated by Django 4.0.4 on 2022-07-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
