# Generated by Django 4.0.4 on 2022-07-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_first_name_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='Empty', max_length=30, verbose_name='Userame'),
        ),
    ]
