# Generated by Django 4.0.4 on 2022-05-10 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('raw_material', '0002_alter_waredata_ware_price_alter_waredata_ware_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productacquisition',
            name='acquisitor_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Beszerző'),
        ),
    ]
