# Generated by Django 4.0.4 on 2022-05-10 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('raw_material', '0003_alter_productacquisition_acquisitor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productacquisition',
            name='acquisition_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Beszerzés dátuma'),
        ),
        migrations.AddField(
            model_name='productacquisition',
            name='store_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Raktározás dátuma'),
        ),
        migrations.AlterField(
            model_name='productacquisition',
            name='acquisitor_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Beszerző', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productacquisition',
            name='store_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Bevételezte', to=settings.AUTH_USER_MODEL),
        ),
    ]
