# Generated by Django 4.0.4 on 2022-05-11 09:37

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('raw_material', '0005_alter_productacquisition_ware_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productacquisition',
            name='acquisitor_user',
            field=models.ForeignKey(default=accounts.models.User, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Beszerző', to=settings.AUTH_USER_MODEL, verbose_name='Beszerző'),
        ),
        migrations.AlterField(
            model_name='productacquisition',
            name='store_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Bevételezte', to=settings.AUTH_USER_MODEL, verbose_name='Bevételezte'),
        ),
        migrations.AlterField(
            model_name='productacquisition',
            name='ware_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Áru', to='raw_material.waredata', verbose_name='Áru'),
        ),
    ]
