# Generated by Django 4.0.4 on 2022-05-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0006_alter_productacquisition_acquisitor_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waretypes',
            name='ware_image',
            field=models.CharField(default='', max_length=100, verbose_name='Ikonja'),
        ),
    ]
