# Generated by Django 4.0.4 on 2022-05-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0008_productacquisition_acquisition_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productacquisition',
            old_name='acquisitor_user',
            new_name='acquisiton_user',
        ),
        migrations.AlterField(
            model_name='waredata',
            name='ware_weight',
            field=models.IntegerField(default=0, verbose_name='Csomag tömege [g]'),
        ),
    ]
