# Generated by Django 4.0.4 on 2022-05-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0010_alter_productacquisition_acquisition_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productacquisition',
            name='acquisition_date',
            field=models.DateTimeField(blank=True, default=0, verbose_name='Beszerzés dátuma'),
        ),
    ]
