# Generated by Django 4.0.4 on 2022-05-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0013_alter_productacquisition_store_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productacquisition',
            name='acquisition_date',
            field=models.DateTimeField(blank=True, default=0, null=True, verbose_name='Beszerzés dátuma'),
        ),
        migrations.AlterField(
            model_name='productacquisition',
            name='store_date',
            field=models.DateTimeField(blank=True, default=0, null=True, verbose_name='Raktározás dátuma'),
        ),
    ]
