# Generated by Django 4.0.4 on 2022-05-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0016_productacquisition_empty_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productacquisition',
            name='store_status',
            field=models.IntegerField(choices=[(1, 'Beszerezve'), (2, 'Bevételezve'), (3, 'Kibontva'), (4, 'Elfogyott')], default=0),
        ),
    ]
