# Generated by Django 4.0.4 on 2022-05-19 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0017_productacquisition_store_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productacquisition',
            name='empty_box',
        ),
        migrations.RemoveField(
            model_name='productacquisition',
            name='open_box',
        ),
        migrations.RemoveField(
            model_name='productacquisition',
            name='stores',
        ),
    ]
