# Generated by Django 4.0.4 on 2022-05-19 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('raw_material', '0018_remove_productacquisition_empty_box_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productacquisition',
            name='acquisition',
        ),
        migrations.AddField(
            model_name='productacquisition',
            name='empty_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Leírta', to=settings.AUTH_USER_MODEL, verbose_name='Leírta'),
        ),
        migrations.AddField(
            model_name='productacquisition',
            name='open_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Kibontotta', to=settings.AUTH_USER_MODEL, verbose_name='Kibontotta'),
        ),
        migrations.AlterField(
            model_name='productacquisition',
            name='open_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Kifogyás dátuma'),
        ),
    ]
