# Generated by Django 4.0.4 on 2022-05-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0019_remove_productacquisition_acquisition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productacquisition',
            name='store_status',
            field=models.IntegerField(choices=[(0, 'Mindegyik'), (1, 'Beszerezve'), (2, 'Raktáron'), (3, 'Kibontva'), (4, 'Elfogyott')], default=0, verbose_name='Raktározási státusz'),
        ),
    ]
