# Generated by Django 4.0.4 on 2022-05-20 09:19

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('raw_material', '0020_alter_productacquisition_store_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeBoile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_boile_dose', models.IntegerField(default=4, verbose_name='Adag')),
                ('c_boile_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Rögzítés dátuma')),
                ('c_boile_user', models.ForeignKey(default=accounts.models.User, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Lefőzte', to=settings.AUTH_USER_MODEL, verbose_name='Lefőzte')),
                ('c_boile_ware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raw_material.productacquisition')),
            ],
        ),
    ]
