# Generated by Django 4.0.4 on 2022-06-19 15:23

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('raw_material', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_make_dose', models.DecimalField(decimal_places=1, default=4, max_digits=2, verbose_name='Adag')),
                ('c_make_date', models.DateTimeField(blank=True, null=True, verbose_name='Elkészül:')),
                ('c_reg_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Rögzítés dátuma')),
                ('c_book', models.DateTimeField(blank=True, null=True, verbose_name='Könyvelés dátuma')),
                ('c_make_user', models.ForeignKey(default=accounts.models.User, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Lefőzte', to=settings.AUTH_USER_MODEL, verbose_name='Lefőzte')),
                ('c_make_ware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raw_material.productacquisition', verbose_name='Kávé fajta')),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee_dose', models.DecimalField(decimal_places=1, default=0.5, max_digits=2, verbose_name='Kávé [0,5-2] Adag')),
                ('sugar_dose', models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Cukor [0,5-3] Adag [5 g]')),
                ('milk_dose', models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Tej [0,5-4] Adag [50 ml]')),
                ('flavour_dose', models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Ízesítő [0,5-2] Adag [5 g]')),
                ('coffee_reg', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Rögzítés dátuma')),
                ('coffe_user', models.ForeignKey(default=accounts.models.User, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Lefoglalta', to=settings.AUTH_USER_MODEL, verbose_name='Lefoglalta')),
                ('coffee_selected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.coffeemake', verbose_name='Lefoglalt Kávé')),
                ('flavour_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strict_flavour', to='raw_material.productacquisition', verbose_name='Lefoglalt Ízesítő')),
                ('milk_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strict_milk', to='raw_material.productacquisition', verbose_name='Lefoglalt Tej')),
                ('sugar_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strict_sugar', to='raw_material.productacquisition', verbose_name='Lefoglalt Cukor')),
            ],
        ),
    ]
