# Generated by Django 4.0.4 on 2022-06-21 12:31

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeemake',
            name='c_order_yes',
            field=models.BooleanField(default=False, verbose_name='Have Order'),
        ),
        migrations.AlterField(
            model_name='coffeemake',
            name='c_book',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Accounting Date'),
        ),
        migrations.AlterField(
            model_name='coffeemake',
            name='c_make_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name="It's done:"),
        ),
        migrations.AlterField(
            model_name='coffeemake',
            name='c_make_dose',
            field=models.DecimalField(decimal_places=1, default=4, max_digits=2, verbose_name='Dose'),
        ),
        migrations.AlterField(
            model_name='coffeemake',
            name='c_make_user',
            field=models.ForeignKey(default=accounts.models.User, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Cooked', to=settings.AUTH_USER_MODEL, verbose_name='Cooked'),
        ),
        migrations.AlterField(
            model_name='coffeemake',
            name='c_make_ware',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raw_material.productacquisition', verbose_name='Kind of coffee'),
        ),
        migrations.AlterField(
            model_name='coffeemake',
            name='c_reg_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date recorded'),
        ),
    ]
