# Generated by Django 4.0.4 on 2022-05-28 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_coffeeorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffeeorder',
            old_name='coffe_selected',
            new_name='coffee_selected',
        ),
    ]
