# Generated by Django 4.0.4 on 2022-05-20 11:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_coffeeboile_coffeemake_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeemake',
            name='c_reg_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Rögzítés dátuma'),
        ),
    ]
