# Generated by Django 4.0.4 on 2022-05-21 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0020_alter_productacquisition_store_status'),
        ('shop', '0003_coffeemake_c_reg_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeemake',
            name='c_make_date',
        ),
        migrations.AddField(
            model_name='coffeemake',
            name='c_make_datetime',
            field=models.DateTimeField(blank=True, default=0, null=True, verbose_name='Elkészül:'),
        ),
        migrations.AlterField(
            model_name='coffeemake',
            name='c_make_ware',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raw_material.productacquisition', verbose_name='Kávé fajta'),
        ),
    ]
