# Generated by Django 4.0.4 on 2022-05-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_coffe_selected_coffeeorder_coffee_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeorder',
            name='flavour_dose',
            field=models.IntegerField(default=1, verbose_name='Ízesítő Adag'),
        ),
    ]
