# Generated by Django 4.0.4 on 2022-05-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_coffeemake_c_make_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeemake',
            name='c_make_datetime',
        ),
        migrations.AddField(
            model_name='coffeemake',
            name='c_make_date',
            field=models.DateTimeField(blank=True, default='', null=True, verbose_name='Elkészül:'),
        ),
    ]
