# Generated by Django 4.0.4 on 2022-05-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_coffeeorder_flavour_dose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeemake',
            name='c_make_dose',
            field=models.DecimalField(decimal_places=1, default=4, max_digits=2, verbose_name='Adag'),
        ),
        migrations.AlterField(
            model_name='coffeeorder',
            name='coffee_dose',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=2, verbose_name='Kávé [0,5-2] Adag'),
        ),
        migrations.AlterField(
            model_name='coffeeorder',
            name='flavour_dose',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=2, verbose_name='Ízesítő [0,5-2] Adag [5 g]'),
        ),
        migrations.AlterField(
            model_name='coffeeorder',
            name='milk_dose',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=2, verbose_name='Tej [0,5-4] Adag [50 ml]'),
        ),
        migrations.AlterField(
            model_name='coffeeorder',
            name='sugar_dose',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=2, verbose_name='Cukor [0,5-3] Adag [5 g]'),
        ),
    ]
