# Generated by Django 4.0.4 on 2022-06-01 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0001_initial'),
        ('shop', '0006_coffeeorder_sugar_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeorder',
            name='milk_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strict_milk', to='raw_material.productacquisition', verbose_name='Lefoglalt Tej'),
        ),
        migrations.AlterField(
            model_name='coffeeorder',
            name='sugar_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strict_sugar', to='raw_material.productacquisition', verbose_name='Lefoglalt Cukor'),
        ),
        migrations.AlterUniqueTogether(
            name='coffeeorder',
            unique_together={('sugar_choice', 'milk_choice')},
        ),
    ]
