# Generated by Django 4.0.4 on 2022-06-01 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0001_initial'),
        ('shop', '0007_coffeeorder_milk_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeorder',
            name='flavour_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strict_flavour', to='raw_material.productacquisition', verbose_name='Lefoglalt Ízesítő'),
        ),
    ]
