# Generated by Django 4.0.4 on 2022-06-13 13:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_coffeeorder_flavour_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeorder',
            name='coffee_book',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Könyvelés dátuma'),
        ),
        migrations.AlterField(
            model_name='coffeeorder',
            name='coffee_dose',
            field=models.DecimalField(decimal_places=1, default=0.5, max_digits=2, verbose_name='Kávé [0,5-2] Adag'),
        ),
    ]
