# Generated by Django 4.0.4 on 2022-06-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_coffeeorder_coffee_book_coffeemake_c_book'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coffeeorder',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='coffeemake',
            name='c_book',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Könyvelés dátuma'),
        ),
    ]
