# Generated by Django 4.0.4 on 2022-05-09 15:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('material1', models.IntegerField(default=0)),
                ('material2', models.IntegerField(default=0)),
                ('material3', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='WareTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ware_types', models.CharField(max_length=10, verbose_name='Anyag fajta')),
                ('ware_wght', models.IntegerField(default=0, verbose_name='Egységnyi tömeg [g]')),
            ],
            options={
                'ordering': ['ware_types'],
            },
        ),
        migrations.CreateModel(
            name='WareData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ware_brand', models.CharField(max_length=50, verbose_name='Márkája')),
                ('ware_brand_name', models.CharField(max_length=50, verbose_name='Fajtája')),
                ('ware_weight', models.IntegerField(default=0, verbose_name='Csomag tömege [g]')),
                ('ware_price', models.IntegerField(default=0, verbose_name='Csomag ára [g]')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Rögzítés dátuma')),
                ('ware_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raw_material.waretypes')),
            ],
        ),
    ]
