# Generated by Django 4.0.4 on 2022-08-14 13:32

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WareTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ware_types', models.CharField(max_length=10, verbose_name='Anyag fajta')),
                ('ware_wght', models.IntegerField(default=0, verbose_name='Egységnyi tömeg [g]')),
                ('ware_image', models.CharField(default='', max_length=100, verbose_name='Ikonja')),
            ],
            options={
                'ordering': ['ware_types'],
            },
        ),
        migrations.CreateModel(
            name='WareData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ware_brand', models.CharField(max_length=50, verbose_name='Márkája')),
                ('ware_brand_name', models.CharField(max_length=50, verbose_name='Fajtája')),
                ('ware_weight', models.IntegerField(default=0, verbose_name='Csomag tömege [g]')),
                ('ware_price', models.IntegerField(default=0, verbose_name='Csomag ára [Ft]')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Rögzítés dátuma')),
                ('ware_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raw_material.waretypes')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAcquisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_status', models.IntegerField(choices=[(0, 'Mindegyik'), (1, 'Beszerezve'), (2, 'Raktáron'), (3, 'Kibontva'), (4, 'Elfogyott')], default=0, verbose_name='Raktározási státusz')),
                ('acquisition_price', models.IntegerField(default=0, verbose_name='Ára [Ft]')),
                ('acquisition_date', models.DateTimeField(blank=True, null=True, verbose_name='Beszerzés dátuma')),
                ('store_date', models.DateTimeField(blank=True, null=True, verbose_name='Raktározás dátuma')),
                ('stock', models.IntegerField(default=0, verbose_name='Készleten [g]')),
                ('open_date', models.DateTimeField(blank=True, null=True, verbose_name='Kibontás dátuma')),
                ('empty_date', models.DateTimeField(blank=True, null=True, verbose_name='Kifogyás dátuma')),
                ('acquisiton_user', models.ForeignKey(default=accounts.models.User, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Beszerző', to=settings.AUTH_USER_MODEL, verbose_name='Beszerző')),
                ('empty_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Leírta', to=settings.AUTH_USER_MODEL, verbose_name='Leírta')),
                ('open_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Kibontotta', to=settings.AUTH_USER_MODEL, verbose_name='Kibontotta')),
                ('store_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Bevételezte', to=settings.AUTH_USER_MODEL, verbose_name='Bevételezte')),
                ('ware_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Áru', to='raw_material.waredata', verbose_name='Áru')),
            ],
        ),
    ]
