# Generated by Django 4.0.4 on 2022-05-10 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waredata',
            name='ware_price',
            field=models.IntegerField(default=0, verbose_name='Csomag ára [Ft]'),
        ),
        migrations.AlterField(
            model_name='waredata',
            name='ware_weight',
            field=models.IntegerField(default=250, verbose_name='Csomag tömege [g]'),
        ),
        migrations.CreateModel(
            name='ProductAcquisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquisitor_user', models.IntegerField(default=0, verbose_name='Beszerző')),
                ('acquisition', models.BooleanField(default=False, verbose_name='Beszerezve [I/N]')),
                ('store_user', models.IntegerField(default=0, verbose_name='Bevételezte')),
                ('stores', models.BooleanField(default=False, verbose_name='Bevételezve [I/N]')),
                ('stock', models.IntegerField(default=0, verbose_name='Készleten [g]')),
                ('ware_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raw_material.waredata')),
            ],
        ),
    ]
