# Generated by Django 4.0.4 on 2022-06-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productacquisition',
            name='open_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Kibontás dátuma'),
        ),
    ]
