# Generated by Django 4.0.4 on 2022-05-06 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waredata',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Rögzítés dátuma'),
        ),
    ]
