# Generated by Django 4.0.4 on 2022-05-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0002_alter_waredata_package_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waredata',
            name='ware_type',
            field=models.CharField(choices=[('coffe', 'Kávé'), ('milks', 'Tej'), ('sugar', 'Cukor'), ('flavo', 'Ízesítő')], default='coffe', max_length=5),
        ),
    ]
