# Generated by Django 4.0.4 on 2022-05-05 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0003_alter_waredata_ware_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waredata',
            old_name='package_weight',
            new_name='ware_weight',
        ),
    ]
