# Generated by Django 4.0.4 on 2022-05-10 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0004_productacquisition_acquisition_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productacquisition',
            name='ware_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Áru', to='raw_material.waredata'),
        ),
    ]
