# Generated by Django 4.0.4 on 2022-05-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0014_alter_productacquisition_acquisition_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productacquisition',
            name='empty_box',
            field=models.BooleanField(default=False, verbose_name='Elfogyott [I/N]'),
        ),
        migrations.AddField(
            model_name='productacquisition',
            name='open_box',
            field=models.BooleanField(default=False, verbose_name='Megkezdve [I/N]'),
        ),
        migrations.AlterField(
            model_name='productacquisition',
            name='acquisition_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Beszerzés dátuma'),
        ),
        migrations.AlterField(
            model_name='productacquisition',
            name='store_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Raktározás dátuma'),
        ),
    ]
