# Generated by Django 4.0.4 on 2022-05-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0015_productacquisition_empty_box_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productacquisition',
            name='empty_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Kifogyás dátuma'),
        ),
        migrations.AddField(
            model_name='productacquisition',
            name='open_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Kibontás dátuma'),
        ),
    ]
