# Generated by Django 4.0.4 on 2022-05-21 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_coffeemake_c_make_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffeemake',
            old_name='c_make_date',
            new_name='c_make_datetime',
        ),
    ]
