# Generated by Django 4.0.4 on 2022-05-21 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_c_make_date_coffeemake_c_make_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeemake',
            name='c_make_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Elkészül:'),
        ),
    ]
