# Generated by Django 4.0.4 on 2022-05-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_coffeemake_c_make_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeemake',
            name='c_make_datetime',
        ),
        migrations.AddField(
            model_name='coffeemake',
            name='c_make_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Elkészül:'),
        ),
    ]
